### ISSUE TITLE
Fix for BettingContract

### ISSUE THREAD

**Issue by DavePearce** [DavePearce/DevmProofGen#71]
The `BettingContract` example is failing for reasons unknown.  However, can confirm that `evmil` disassembles it without problem.

```
thread 'main' panicked at 'internal error: entered unreachable code', /home/djp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/evmil-0.4.3/src/bytecode/instruction.rs:316:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:117:5
   3: evmil::bytecode::instruction::Instruction::operands
   4: evmil::analysis::dependency::find_dependencies
   5: evmil::analysis::havoc::insert_havocs
   6: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   7: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   8: devmpg::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by DavePearce** [comment]
Ok, no.  The problem is arising within `evmil::analysis::havoc::insert_havocs`.  So, this is an EvmIL bug.

**Comment by DavePearce** [comment]
Done and fixed.
